# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

sim, objetos compostos multidimoensionais podem receber objetos compostos unidimensionais dentro deles. um exemplo seria:

In [1]:
obj_multi = [
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
]

obj_multi

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [2]:
%run "objetos compostos 1.ipynb"

1
macaco
3.14
true
13
0
0
0
0
0
[42, 3.14, 2.718]
a
s
<class 'dict'>
<class 'int'>
5
['ROP16', 'ROP18', 'GRA7', 'SAG2', 'IL6']

In [3]:
nomes_genes =['ROP16', 'ROP18', 'GRA7', 'SAG2', 'IL6']
gene_um = [len (lista_gene [0]),
           lista_gene[0][:2],
           lista_gene[0].count('a'),
           'hu' in lista_gene [0]]
gene_um

gene_dois = [len (lista_gene [1]),
           lista_gene[1][:2],
           lista_gene[1].count('a'),
           'hu' in lista_gene [1]]
gene_dois

gene_tres = [len (lista_gene [2]),
           lista_gene[2][:2],
           lista_gene[2].count('a'),
           'hu' in lista_gene [2]]
gene_tres

gene_quatro = [len (lista_gene [3]),
           lista_gene[3][:2],
           lista_gene[3].count('a'),
           'hu' in lista_gene [3]]
gene_quatro

gene_cinco = [len (lista_gene [4]),
           lista_gene[4][:2],
           lista_gene[4].count('a'),
           'hu' in lista_gene [4]]
gene_cinco

[3, 'IL', 0, False]

In [4]:
obj_multi_genes = [gene_um, gene_dois, gene_tres, gene_quatro, gene_cinco]
obj_multi_genes

[[5, 'RO', 0, False],
 [5, 'RO', 0, False],
 [4, 'GR', 0, False],
 [4, 'SA', 0, False],
 [3, 'IL', 0, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [5]:
import numpy as np

In [6]:
array_ex3 = np.array(obj_multi_genes)
array_ex3

array([['5', 'RO', '0', 'False'],
       ['5', 'RO', '0', 'False'],
       ['4', 'GR', '0', 'False'],
       ['4', 'SA', '0', 'False'],
       ['3', 'IL', '0', 'False']], dtype='<U21')

## 4 – Recupere todos os itens do terceiro gene.

In [7]:
array_ex3[2, :]

array(['4', 'GR', '0', 'False'], dtype='<U21')

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [8]:
"hu" in array_ex3

False

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [9]:
array_ex3[1, 1:3], array_ex3[3, 1:3]

(array(['RO', '0'], dtype='<U21'), array(['SA', '0'], dtype='<U21'))

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [10]:
import pandas as pd

In [11]:
dict_gene_final

{'ROP16': [5, 'RO', 0, False],
 'ROP18': [5, 'RO', 0, False],
 'GRA7': [4, 'GR', 0, False],
 'SAG2': [4, 'SA', 0, False],
 'IL6': [3, 'IL', 0, False]}

In [12]:
df_ex7 = pd.DataFrame(dict_gene_final).T
df_rename = df_ex7.rename(columns={0: 'n_caracteres', 
                                   1: '2_primeiras_letras', 
                                   2: 'n_a', 
                                   3: 'hu'})
df_rename

      n_caracteres 2_primeiras_letras n_a     hu
ROP16            5                 RO   0  False
ROP18            5                 RO   0  False
GRA7             4                 GR   0  False
SAG2             4                 SA   0  False
IL6              3                 IL   0  False

In [27]:
import pandas as pd

In [30]:
df_rename.to_csv('array_ex7_aula6.csv')

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [13]:
df_rename[['n_caracteres', 'n_a']]

      n_caracteres n_a
ROP16            5   0
ROP18            5   0
GRA7             4   0
SAG2             4   0
IL6              3   0

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [14]:
df_rename.loc[df_rename.index [[0,3]], 'hu']

ROP16    False
SAG2     False
Name: hu, dtype: object

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [15]:
import os

In [16]:
os.listdir()

['10-Estruturas_condicionais_2026-03-26.ipynb',
 '09-Operadores_lógicos_2026-03-25.ipynb',
 'objetos simples.ipynb',
 '08-Operadores_relacionais_2026-03-24.ipynb',
 'Objetos Compostos 2.ipynb',
 'exercicio 01.ipynb',
 '07-Operadores_aritméticos_2026-03-23.ipynb',
 'objetos compostos 1.ipynb',
 'img']

In [17]:
df_ex10 = pd.read_csv('/home/nina/Documents/Aula git/Data/data.csv')

In [18]:
df_ex10.head()

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1

In [19]:
entradas = len(df_ex10)

In [20]:
tipos_colunas = df_ex10.dtypes.tolist()

In [21]:
contagem = df_ex10.dtypes.value_counts().tolist()

In [22]:
lista_entradas = df_ex10.iloc[:,0]
lista_colunas = df_ex10.iloc [:,3]
lista_elementos = df_ex10.iloc[:,8]
print(lista_entradas, lista_colunas, lista_elementos)

0        119736
1        448094
2        206893
3        333743
4        172534
          ...
36629    404309
36630    465875
36631    791209
36632    322627
36633    398149
Name: policyID, Length: 36634, dtype: int64 0         498960.0
1        1322376.3
2         190724.4
3              0.0
4              0.0
           ...
36629          0.0
36630    1297057.5
36631     173286.9
36632    1499781.6
36633     373488.3
Name: eq_site_limit, Length: 36634, dtype: float64 0         792148.90
1        1438163.57
2         192476.78
3          86854.48
4         246144.49
            ...
36629     155065.65
36630    1577500.79
36631     205527.97
36632    1768782.43
36633     596003.67
Name: tiv_2012, Length: 36634, dtype: float64

In [23]:
media = [lista_entradas.mean(), 
         lista_colunas.mean(), 
         lista_elementos.mean()
]
media

[np.float64(548661.9371894961),
 np.float64(731478.0068460993),
 np.float64(2571004.0973420865)]

In [24]:
desvio = [lista_entradas.std(),
          lista_colunas.std(),
          lista_elementos.std()
]
desvio

[np.float64(259912.9264939009),
 np.float64(17523003.588415086),
 np.float64(20367766.569178067)]

In [25]:
quartil = [lista_entradas.quantile(0.75),
           lista_colunas.quantile(0.75),
           lista_elementos.quantile(0.75)
]
quartil

[np.float64(774252.0), np.float64(0.0), np.float64(1128871.1824999999)]

In [26]:
dict_final_ex10 = {
    'n entradas': entradas,
    'tipos colunas': tipos_colunas,
    'contagem': contagem,
    'media': media,
    'desvio': desvio,
    'quartil': quartil
}
dict_final_ex10

{'n entradas': 36634,
 'tipos colunas': [dtype('int64'),
  dtype('O'),
  dtype('O'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('float64'),
  dtype('int64'),
  dtype('float64'),
  dtype('float64'),
  dtype('O'),
  dtype('O'),
  dtype('int64')],
 'contagem': [11, 4, 3],
 'media': [np.float64(548661.9371894961),
  np.float64(731478.0068460993),
  np.float64(2571004.0973420865)],
 'desvio': [np.float64(259912.9264939009),
  np.float64(17523003.588415086),
  np.float64(20367766.569178067)],
 'quartil': [np.float64(774252.0),
  np.float64(0.0),
  np.float64(1128871.1824999999)]}