# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

sim, objetos compostos multidimoensionais podem receber objetos compostos unidimensionais dentro deles. um exemplo seria:

In [ ]:
obj_multi = [
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
]

obj_multi

[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [1]:
%run "objetos compostos 1.ipynb"

1
macaco
3.14
true
13
0
0
0
0
0
[42, 3.14, 2.718]
a
s
<class 'dict'>
<class 'int'>
5
['ROP16', 'ROP18', 'GRA7', 'SAG2', 'IL6']

In [ ]:
nomes_genes =['ROP16', 'ROP18', 'GRA7', 'SAG2', 'IL6']
gene_um = [len (lista_gene [0]),
           lista_gene[0][:2],
           lista_gene[0].count('a'),
           'hu' in lista_gene [0]]
gene_um

gene_dois = [len (lista_gene [1]),
           lista_gene[1][:2],
           lista_gene[1].count('a'),
           'hu' in lista_gene [1]]
gene_dois

gene_tres = [len (lista_gene [2]),
           lista_gene[2][:2],
           lista_gene[2].count('a'),
           'hu' in lista_gene [2]]
gene_tres

gene_quatro = [len (lista_gene [3]),
           lista_gene[3][:2],
           lista_gene[3].count('a'),
           'hu' in lista_gene [3]]
gene_quatro

gene_cinco = [len (lista_gene [4]),
           lista_gene[4][:2],
           lista_gene[4].count('a'),
           'hu' in lista_gene [4]]
gene_cinco

['ROP16', 'ROP18', 'GRA7', 'SAG2', 'IL6']

In [4]:
obj_multi_genes = [gene_um, gene_dois, gene_tres, gene_quatro, gene_cinco]
obj_multi_genes

[[5, 'RO', 0, False],
 [5, 'RO', 0, False],
 [4, 'GR', 0, False],
 [4, 'SA', 0, False],
 [3, 'IL', 0, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [5]:
import numpy as np

In [6]:
array_ex3 = np.array(obj_multi_genes)
array_ex3

array([['5', 'RO', '0', 'False'],
       ['5', 'RO', '0', 'False'],
       ['4', 'GR', '0', 'False'],
       ['4', 'SA', '0', 'False'],
       ['3', 'IL', '0', 'False']], dtype='<U21')

## 4 – Recupere todos os itens do terceiro gene.

In [7]:
array_ex3[2, :]

array(['4', 'GR', '0', 'False'], dtype='<U21')

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [8]:
"hu" in array_ex3

False

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [13]:
array_ex3[1, 1:3], array_ex3[3, 1:3]

(array(['RO', '0'], dtype='<U21'), array(['SA', '0'], dtype='<U21'))

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [14]:
import pandas as pd

In [15]:
dict_gene_final

{'ROP16': [5, 'RO', 0, False],
 'ROP18': [5, 'RO', 0, False],
 'GRA7': [4, 'GR', 0, False],
 'SAG2': [4, 'SA', 0, False],
 'IL6': [3, 'IL', 0, False]}

In [ ]:
df_ex7 = pd.DataFrame(dict_gene_final).T
df_rename = df_ex7.rename(columns={0: 'n_caracteres', 
                                   1: '2_primeiras_letras', 
                                   2: 'n_a', 
                                   3: 'hu'})
df_rename

      n_caracteres 2_primeiras_letras n_a     hu
ROP16            5                 RO   0  False
ROP18            5                 RO   0  False
GRA7             4                 GR   0  False
SAG2             4                 SA   0  False
IL6              3                 IL   0  False

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [22]:
df_rename[['n_caracteres', 'n_a']]

      n_caracteres n_a
ROP16            5   0
ROP18            5   0
GRA7             4   0
SAG2             4   0
IL6              3   0

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [28]:
df_rename.loc[df_rename.index [[0,3]], 'hu']

ROP16    False
SAG2     False
Name: hu, dtype: object

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [44]:
import os